<?php
namespace frontend\controllers;

use Yii;
use yii\web\Controller;

class HomeController extends Controller
{
    public function beforeAction($action)
    {

        $app=Yii::$app;
        if($app->user->isGuest)
        {
            $this->redirect("/site/login");
			return ;
        }

        return parent::beforeAction($action); // TODO: Change the autogenerated stub

    }
}